dashboard_path = '/Users/sankalpg/Documents/Project/aag/src/pages/Admin/Dashboard.jsx'
with open(dashboard_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# 1. Insert Top Sub-Tabs Row inside form tag (around line 1142)
form_line_idx = -1
for idx, line in enumerate(lines):
    if 'className="admin-form-container"' in line:
        form_line_idx = idx
        break

if form_line_idx != -1:
    sub_tabs_bar = [
        ' {/* Home Manager Sub-Tab Navigation Bar */}\n',
        ' <div style={{ display: \'flex\', gap: \'8px\', marginBottom: \'24px\', borderBottom: \'2px solid rgba(226, 215, 197, 0.4)\', paddingBottom: \'12px\', flexWrap: \'wrap\' }}>\n',
        ' <button\n',
        ' type="button"\n',
        ' className={`admin-btn ${activeTab === \'hero\' || activeTab === \'banner\' ? \'phoenix-btn-primary\' : \'admin-btn-secondary\'}`}\n',
        ' onClick={() => setActiveTab(\'hero\')}\n',
        ' style={{ padding: \'6px 16px\', fontSize: \'0.88rem\', fontWeight: 600 }}\n',
        ' >\n',
        ' 1. {tLabel(\'बैनर\', \'Banner\')}\n',
        ' </button>\n',
        ' <button\n',
        ' type="button"\n',
        ' className={`admin-btn ${activeTab === \'about\' || activeTab === \'intro\' ? \'phoenix-btn-primary\' : \'admin-btn-secondary\'}`}\n',
        ' onClick={() => setActiveTab(\'about\')}\n',
        ' style={{ padding: \'6px 16px\', fontSize: \'0.88rem\', fontWeight: 600 }}\n',
        ' >\n',
        ' 2. {tLabel(\'परिचय\', \'About\')}\n',
        ' </button>\n',
        ' <button\n',
        ' type="button"\n',
        ' className={`admin-btn ${activeTab === \'featured\' || activeTab === \'poetry\' ? \'phoenix-btn-primary\' : \'admin-btn-secondary\'}`}\n',
        ' onClick={() => setActiveTab(\'featured\')}\n',
        ' style={{ padding: \'6px 16px\', fontSize: \'0.88rem\', fontWeight: 600 }}\n',
        ' >\n',
        ' 3. {tLabel(\'विशेष कविताएं\', \'Featured Poetry\')}\n',
        ' </button>\n',
        ' <button\n',
        ' type="button"\n',
        ' className={`admin-btn ${activeTab === \'books\' ? \'phoenix-btn-primary\' : \'admin-btn-secondary\'}`}\n',
        ' onClick={() => setActiveTab(\'books\')}\n',
        ' style={{ padding: \'6px 16px\', fontSize: \'0.88rem\', fontWeight: 600 }}\n',
        ' >\n',
        ' 4. {tLabel(\'विशेष पुस्तकें\', \'Featured Books\')}\n',
        ' </button>\n',
        ' </div>\n'
    ]
    lines = lines[:form_line_idx + 2] + sub_tabs_bar + lines[form_line_idx + 2:]
    print("Top sub-tabs bar inserted at index", form_line_idx + 2)

# Update activeTab check for Banner
for idx in range(len(lines)):
    if "{activeTab === 'hero' && (" in lines[idx]:
        lines[idx] = " {(activeTab === 'hero' || activeTab === 'banner') && (\n"
        break

# Find MODULE 3 start
mod3_start = -1
for idx, line in enumerate(lines):
    if 'MODULE 3: FEATURED WORKS SHOWCASE' in line:
        mod3_start = idx
        break

if mod3_start != -1:
    # Find form closing tag </form> after mod3_start
    form_close_idx = -1
    for i in range(mod3_start, len(lines)):
        if '</form>' in lines[i]:
            form_close_idx = i
            break

    if form_close_idx != -1:
        new_modules_3_and_4 = [
            ' {/* MODULE 3: FEATURED POETRY */}\n',
            ' {(activeTab === \'featured\' || activeTab === \'poetry\') && (\n',
            ' <div>\n',
            ' <h3 style={{ fontFamily: \'Lora, serif\', fontSize: \'1.1rem\', color: \'var(--leona-charcoal)\', marginBottom: \'16px\' }}>\n',
            ' {tLabel(\'विशेष कविताएं (Featured Poetry)\', \'Featured Poetry\')}\n',
            ' </h3>\n',
            '\n',
            ' {/* Single Row Limit Configuration */}\n',
            ' <div style={{ background: \'#FFF\', padding: \'18px\', borderRadius: \'10px\', border: \'1px solid rgba(226, 215, 197, 0.8)\', marginBottom: \'24px\' }}>\n',
            ' <div style={{ maxWidth: \'320px\' }}>\n',
            ' <label style={{ display: \'block\', fontWeight: 600, fontSize: \'0.9rem\', marginBottom: \'6px\', color: \'#1e293b\' }}>\n',
            ' {tLabel(\'काव्य संग्रह कार्ड सीमा (Max Poems on Home Page)\', \'Max Poems on Home Page\')}\n',
            ' </label>\n',
            ' <input\n',
            ' type="number"\n',
            ' min="1"\n',
            ' max="10"\n',
            ' className="admin-input"\n',
            ' value={poemsLimit}\n',
            ' onChange={(e) => {\n',
            ' setPoemsLimit(Math.max(1, parseInt(e.target.value || \'1\', 10)))\n',
            ' if (setIsDirty) setIsDirty(true)\n',
            ' }}\n',
            ' />\n',
            ' </div>\n',
            ' <p style={{ margin: \'8px 0 0 0\', fontSize: \'0.85rem\', color: \'#64748b\', fontStyle: \'italic\' }}>\n',
            ' {tLabel(\'होम पेज पर दिखने वाले काव्य कार्ड्स की अधिकतम संख्या set करें।\', \'Set maximum number of poem cards displayed on the public home page.\')}\n',
            ' </p>\n',
            ' </div>\n',
            '\n',
            ' {/* Featured Poems List */}\n',
            ' <div style={{ background: \'#FFF\', padding: \'18px\', borderRadius: \'10px\', border: \'1px solid rgba(226, 215, 197, 0.8)\' }}>\n',
            ' <div style={{ display: \'flex\', justifyContent: \'space-between\', alignItems: \'center\', marginBottom: \'14px\' }}>\n',
            ' <h4 style={{ margin: 0, fontFamily: \'Lora, serif\', fontSize: \'1.05rem\', color: \'var(--leona-charcoal)\' }}>\n',
            ' {tLabel(\'मुख्य पृष्ठ काव्य रचनाएं (Featured Poems)\', \'Featured Poems\')}\n',
            ' </h4>\n',
            ' <span className="admin-toolbar-count">\n',
            ' {featuredPoems.length}/6 {tLabel(\'रचनाएं चयनित\', \'Poems Selected\')}\n',
            ' </span>\n',
            ' </div>\n',
            '\n',
            ' <div style={{ display: \'flex\', gap: \'10px\', marginBottom: \'16px\' }}>\n',
            ' <select\n',
            ' className="admin-input"\n',
            ' style={{ flex: 1 }}\n',
            ' value=""\n',
            ' onChange={(e) => {\n',
            ' const id = e.target.value\n',
            ' if (id && !featuredPoems.includes(id)) {\n',
            ' if (featuredPoems.length >= 6) {\n',
            ' alert(tLabel(\'अधिकतम 6 रचनाएं ही चुनी जा सकती हैं।\', \'Maximum 6 poems allowed.\'))\n',
            ' return\n',
            ' }\n',
            ' setFeaturedPoems([...featuredPoems, id])\n',
            ' if (setIsDirty) setIsDirty(true)\n',
            ' }\n',
            ' }}\n',
            ' >\n',
            ' <option value="">-- {tLabel(\'काव्य संग्रह से रचना चुनें व जोड़ें...\', \'Select poem to add to featured list...\')} --</option>\n',
            ' {safePoems\n',
            ' .filter(p => !featuredPoems.includes(p.id))\n',
            ' .map(p => (\n',
            ' <option key={p.id} value={p.id}>\n',
            ' {p.heading_hi || p.heading_en || p.heading || \'Untitled\'}\n',
            ' </option>\n',
            ' ))}\n',
            ' </select>\n',
            ' </div>\n',
            '\n',
            ' {featuredPoems.length === 0 ? (\n',
            ' <p style={{ fontStyle: \'italic\', color: \'#888\', margin: 0 }}>{tLabel(\'कोई रचना चयनित नहीं है।\', \'No featured poems selected.\')}</p>\n',
            ' ) : (\n',
            ' <ul className="admin-item-list">\n',
            ' {featuredPoems.map((id, index) => {\n',
            ' const poemObj = safePoems.find(p => p.id === id)\n',
            ' return (\n',
            ' <li key={id} className="admin-item-card" style={{ justifyContent: \'space-between\' }}>\n',
            ' <div style={{ display: \'flex\', alignItems: \'center\', gap: \'10px\' }}>\n',
            ' <span style={{ fontWeight: 700, width: \'24px\', height: \'24px\', background: \'var(--leona-terracotta)\', color: \'#FFF\', borderRadius: \'50%\', display: \'flex\', alignItems: \'center\', justifyContent: \'center\', fontSize: \'0.8rem\' }}>\n',
            ' {index + 1}\n',
            ' </span>\n',
            ' <span style={{ fontWeight: 600, color: \'var(--leona-charcoal)\' }}>\n',
            ' {poemObj ? (poemObj.heading_hi || poemObj.heading_en || poemObj.heading) : `Poem ID: ${id}`}\n',
            ' </span>\n',
            ' </div>\n',
            ' <div style={{ display: \'flex\', alignItems: \'center\', gap: \'8px\' }}>\n',
            ' <button type="button" className="admin-btn-secondary" onClick={() => setFeaturedPoems(moveItemInArray(featuredPoems, index, \'up\'))} disabled={index === 0}>\n',
            ' ⬆️\n',
            ' </button>\n',
            ' <button type="button" className="admin-btn-secondary" onClick={() => setFeaturedPoems(moveItemInArray(featuredPoems, index, \'down\'))} disabled={index === featuredPoems.length - 1}>\n',
            ' ⬇️\n',
            ' </button>\n',
            ' <button type="button" className="admin-btn-danger" onClick={() => { setFeaturedPoems(featuredPoems.filter(item => item !== id)); if (setIsDirty) setIsDirty(true); }}>\n',
            ' 🗑️\n',
            ' </button>\n',
            ' </div>\n',
            ' </li>\n',
            ' )\n',
            ' })}\n',
            ' </ul>\n',
            ' )}\n',
            ' </div>\n',
            ' </div>\n',
            ' )}\n',
            '\n',
            ' {/* MODULE 4: FEATURED BOOKS (NEW TAB) */}\n',
            ' {activeTab === \'books\' && (\n',
            ' <div>\n',
            ' <h3 style={{ fontFamily: \'Lora, serif\', fontSize: \'1.1rem\', color: \'var(--leona-charcoal)\', marginBottom: \'16px\' }}>\n',
            ' {tLabel(\'विशेष पुस्तकें (Featured Books)\', \'Featured Books\')}\n',
            ' </h3>\n',
            '\n',
            ' {/* Single Row Limit Configuration */}\n',
            ' <div style={{ background: \'#FFF\', padding: \'18px\', borderRadius: \'10px\', border: \'1px solid rgba(226, 215, 197, 0.8)\', marginBottom: \'24px\' }}>\n',
            ' <div style={{ maxWidth: \'320px\' }}>\n',
            ' <label style={{ display: \'block\', fontWeight: 600, fontSize: \'0.9rem\', marginBottom: \'6px\', color: \'#1e293b\' }}>\n',
            ' {tLabel(\'प्रकाशन कार्ड सीमा (Max Books on Home Page)\', \'Max Books on Home Page\')}\n',
            ' </label>\n',
            ' <input\n',
            ' type="number"\n',
            ' min="1"\n',
            ' max="10"\n',
            ' className="admin-input"\n',
            ' value={pubsLimit}\n',
            ' onChange={(e) => {\n',
            ' setPubsLimit(Math.max(1, parseInt(e.target.value || \'1\', 10)))\n',
            ' if (setIsDirty) setIsDirty(true)\n',
            ' }}\n',
            ' />\n',
            ' </div>\n',
            ' <p style={{ margin: \'8px 0 0 0\', fontSize: \'0.85rem\', color: \'#64748b\', fontStyle: \'italic\' }}>\n',
            ' {tLabel(\'होम पेज पर दिखने वाले पुस्तक कार्ड्स की अधिकतम संख्या set करें।\', \'Set maximum number of book cards displayed on the public home page.\')}\n',
            ' </p>\n',
            ' </div>\n',
            '\n',
            ' {/* Featured Publications List */}\n',
            ' <div style={{ background: \'#FFF\', padding: \'18px\', borderRadius: \'10px\', border: \'1px solid rgba(226, 215, 197, 0.8)\' }}>\n',
            ' <div style={{ display: \'flex\', justifyContent: \'space-between\', alignItems: \'center\', marginBottom: \'14px\' }}>\n',
            ' <h4 style={{ margin: 0, fontFamily: \'Lora, serif\', fontSize: \'1.05rem\', color: \'var(--leona-charcoal)\' }}>\n',
            ' {tLabel(\'मुख्य पृष्ठ पुस्तकें (Featured Books)\', \'Featured Publications\')}\n',
            ' </h4>\n',
            ' <span className="admin-toolbar-count">\n',
            ' {featuredPubs.length}/6 {tLabel(\'पुस्तकें चयनित\', \'Books Selected\')}\n',
            ' </span>\n',
            ' </div>\n',
            '\n',
            ' <div style={{ display: \'flex\', gap: \'10px\', marginBottom: \'16px\' }}>\n',
            ' <select\n',
            ' className="admin-input"\n',
            ' style={{ flex: 1 }}\n',
            ' value=""\n',
            ' onChange={(e) => {\n',
            ' const id = e.target.value\n',
            ' if (id && !featuredPubs.includes(id)) {\n',
            ' if (featuredPubs.length >= 6) {\n',
            ' alert(tLabel(\'अधिकतम 6 पुस्तकें ही चुनी जा सकती हैं।\', \'Maximum 6 publications allowed.\'))\n',
            ' return\n',
            ' }\n',
            ' setFeaturedPubs([...featuredPubs, id])\n',
            ' if (setIsDirty) setIsDirty(true)\n',
            ' }\n',
            ' }}\n',
            ' >\n',
            ' <option value="">-- {tLabel(\'प्रकाशन सूची से पुस्तक चुनें व जोड़ें...\', \'Select publication to add to featured list...\')} --</option>\n',
            ' {safePubs\n',
            ' .filter(p => !featuredPubs.includes(p.id))\n',
            ' .map(p => (\n',
            ' <option key={p.id} value={p.id}>\n',
            ' {p.title_hi || p.title_en || p.title || \'Untitled\'}\n',
            ' </option>\n',
            ' ))}\n',
            ' </select>\n',
            ' </div>\n',
            '\n',
            ' {featuredPubs.length === 0 ? (\n',
            ' <p style={{ fontStyle: \'italic\', color: \'#888\', margin: 0 }}>{tLabel(\'कोई पुस्तक चयनित नहीं है।\', \'No featured publications selected.\')}</p>\n',
            ' ) : (\n',
            ' <ul className="admin-item-list">\n',
            ' {featuredPubs.map((id, index) => {\n',
            ' const pubObj = safePubs.find(p => p.id === id)\n',
            ' return (\n',
            ' <li key={id} className="admin-item-card" style={{ justifyContent: \'space-between\' }}>\n',
            ' <div style={{ display: \'flex\', alignItems: \'center\', gap: \'10px\'>\n',
            ' <span style={{ fontWeight: 700, width: \'24px\', height: \'24px\', background: \'var(--leona-terracotta)\', color: \'#FFF\', borderRadius: \'50%\', display: \'flex\', alignItems: \'center\', justifyContent: \'center\', fontSize: \'0.8rem\' }}>\n',
            ' {index + 1}\n',
            ' </span>\n',
            ' <span style={{ fontWeight: 600, color: \'var(--leona-charcoal)\' }}>\n',
            ' {pubObj ? (pubObj.title_hi || pubObj.title_en || pubObj.title) : `Publication ID: ${id}`}\n',
            ' </span>\n',
            ' </div>\n',
            ' <div style={{ display: \'flex\', alignItems: \'center\', gap: \'8px\'>\n',
            ' <button type="button" className="admin-btn-secondary" onClick={() => setFeaturedPubs(moveItemInArray(featuredPubs, index, \'up\'))} disabled={index === 0}>\n',
            ' ⬆️\n',
            ' </button>\n',
            ' <button type="button" className="admin-btn-secondary" onClick={() => setFeaturedPubs(moveItemInArray(featuredPubs, index, \'down\'))} disabled={index === featuredPubs.length - 1}>\n',
            ' ⬇️\n',
            ' </button>\n',
            ' <button type="button" className="admin-btn-danger" onClick={() => { setFeaturedPubs(featuredPubs.filter(item => item !== id)); if (setIsDirty) setIsDirty(true); }}>\n',
            ' 🗑️\n',
            ' </button>\n',
            ' </div>\n',
            ' </li>\n',
            ' )\n',
            ' })}\n',
            ' </ul>\n',
            ' )}\n',
            ' </div>\n',
            ' </div>\n',
            ' )\n'
        ]
        lines = lines[:mod3_start] + new_modules_3_and_4 + lines[form_close_idx:]
        print("MODULE 3 and 4 replaced successfully! Highlights & Awards deleted!")

with open(dashboard_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)
